Algoritmo "semnome"
//Funcao: carteira de motorista
//Autor: Igor de jesus Silva
//Data: / /

Var
idade: inteiro
resposta: caracter

Inicio
// Entrada
Escreval ("Qual sua idade: ")
Leia (idade)
Escreval ("possui habilitação:")
Leia (resposta)
//Descisao
Se ((idade>=18) e (resposta="sim")) então
           Escreval ("pode passar")
Senao
          Escreval ("não pode passar")
fimse


Fimalgoritmo
