Algoritmo "volei se"
// 
//Funcao: informa se você pode competir no volei
//Autor: Igor de jesus Silva
//Data: / /
Var
altura,idade: inteiro

Inicio

Escreval ("digite sua idade:")
Leia (idade)
Escreval ("digite sua altura")
Leia (altura)
// Processamento
Se  (altura >= 1.75 E idade >= 18) entao
     Escreval ("você pode competir")
Senão
     escreval ("Você não pode competir")
Fimse



Fimalgoritmo